#ifndef MESSEGES
#define MESSEGES

typedef enum MessegesType {
	CLIENT_REQUEST,
	CLIENT_SETUP,
	CLIENT_PLAYER_MOVE,
	CLIENT_DISCONNECT,
	SERVER_MAIN_MENU,
	SERVER_APPROVED,
	SERVER_DENIED,
	SERVER_INVITE,
	SERVER_SETUP_REQUEST,
	SERVER_PLAYER_MOVE_REQUEST,
	SERVER_GAME_RESULTS,
	SERVER_WIN,
	SERVER_DRAW,
	SERVER_NO_OPPONENTS,
	SERVER_OPPONENT_QUIT

}MessegesType;

typedef struct{
	char* Parameters;
	MessegesType MessegeType;
}Messege;


#endif